/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import clave_dicotomica.BinTree;
import clave_dicotomica.Nodo;
import clave_dicotomica.LeerJson;
import clave_dicotomica.HTable;

import javax.swing.JOptionPane;
/**
 *
 * @author zarna
 */
public class UI extends javax.swing.JFrame {
static BinTree arbol1;
static boolean respuesta = true;
static HTable hashtable;
static HTable hashtable2;
static String rutaArboles;
static String archivo;
Nodo aux = null;
    /**
     * Creates new form UI
     */
    public UI() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hashsearch = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pregunta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        si = new javax.swing.JButton();
        no = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        textoPreguntas = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("CLAVES DICOTOMICAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Familias botanicas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 210, 40));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Arboles templados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 220, 40));

        jLabel2.setText("Bienvenido!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 70, -1));

        jLabel3.setText("COMO DESEA ENCONTRAR LA INFORMACION?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setText("Busqueda por estructura de dato:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 370, 40));

        jLabel5.setText("Tiempo: 0");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        hashsearch.setBackground(new java.awt.Color(204, 255, 204));
        hashsearch.setText("Por hash table");
        hashsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashsearchActionPerformed(evt);
            }
        });
        jPanel1.add(hashsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 30));

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setText("Por arbol ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 30));

        pregunta.setColumns(20);
        pregunta.setRows(5);
        jScrollPane1.setViewportView(pregunta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 290, 430));

        jLabel6.setText("Preguntas que aparecen:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        jLabel8.setText("Por preguntas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        si.setBackground(new java.awt.Color(204, 255, 204));
        si.setText("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        jPanel1.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 190, 30));

        no.setBackground(new java.awt.Color(204, 255, 204));
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 220, 30));

        jButton9.setBackground(new java.awt.Color(204, 255, 204));
        jButton9.setText("Visualizar el arbol");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 550, 80));

        textoPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPreguntasActionPerformed(evt);
            }
        });
        jPanel1.add(textoPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 450, 40));

        OK.setBackground(new java.awt.Color(204, 255, 204));
        OK.setText("OK/RESET");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        jPanel1.add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 120, 40));

        jLabel9.setText("Hecho por Ricardo Fernandez, Leopoldo Roa y Miguel Greco");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jLabel10.setText("PD: El boton de OK/RESET sirve para empezar la parte de las preguntas.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Nodo pNew = new Nodo("Hojas como agujas");
        BinTree arbol = new BinTree();
        arbol.setpRoot(pNew);
        arbol.generarArbol1();
        arbol1 = arbol;
        rutaArboles = "src/clave_dicotomica/arboles_templados.json";
        archivo = "Arboles templados";
        hashtable = LeerJson.procesarJSON(rutaArboles, archivo);
        
        jLabel2.setText("Se ha generado la clave: "+jButton3.getText());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hashsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashsearchActionPerformed
        try{
        pregunta.setText("");
        String value = jTextField1.getText();
        
        String[] arr = hashtable.get(value);
        long tiempo1 = System.nanoTime();
        for(int i=0; i<arr.length; i++){
        pregunta.setText(pregunta.getText()+"\n"+arr[i]);
        long tiempo2 = System.nanoTime();
        jLabel5.setText("Tiempo: " + Long.toString(tiempo2-tiempo1));
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hashsearchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
        pregunta.setText("");
        String value = jTextField1.getText();
        long tiempo1 = System.nanoTime();
        boolean[] ruta = LeerJson.procesarJSON2(rutaArboles, archivo, value);
        aux = arbol1.getpRoot();
        for(int i=0;i<ruta.length;i++){
        if(ruta[i]==true){
            pregunta.setText(pregunta.getText()+"\n"+aux.getInfo()+"= "+ruta[i]);
            aux = aux.getHijo_der(); 
        }else{
            pregunta.setText(pregunta.getText()+"\n"+aux.getInfo()+"= "+ruta[i]);
            aux = aux.getHijo_izq(); 
        }
        }
        long tiempo2 = System.nanoTime();
        jLabel5.setText("Tiempo: " + Long.toString(tiempo2-tiempo1));
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        try{
        respuesta = true;
        aux = aux.getHijo_der();
        textoPreguntas.setText(aux.getInfo());
        pregunta.setText(pregunta.getText()+"\n"+aux.getInfo());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ya no puedes ir mas alla");
        }
       
    }//GEN-LAST:event_siActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textoPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPreguntasActionPerformed
        
    }//GEN-LAST:event_textoPreguntasActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        
        try{
        aux = arbol1.getpRoot();
        textoPreguntas.setText(aux.getInfo());
        pregunta.setText(aux.getInfo());}catch(Exception e){
            JOptionPane.showMessageDialog(null, "No has seleccionado ninguno de los dos archivos");
        }
    }//GEN-LAST:event_OKActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        try{
        respuesta = false;
        aux = aux.getHijo_izq();
        textoPreguntas.setText(aux.getInfo());
        pregunta.setText(pregunta.getText()+"\n"+aux.getInfo());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ya no puedes ir mas alla");
        }
    }//GEN-LAST:event_noActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Nodo pNew = new Nodo("Reproduccion por esporas");
        BinTree arbol = new BinTree();
        arbol.setpRoot(pNew);
        arbol.generarArbol2();
        arbol1 = arbol;
        rutaArboles = "src/clave_dicotomica/familias_botanicas.json";
        archivo = "Familias botánicas";
        hashtable = LeerJson.procesarJSON(rutaArboles, archivo);
        jLabel2.setText("Se ha generado la clave: "+jButton1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JButton hashsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton no;
    private javax.swing.JTextArea pregunta;
    private javax.swing.JButton si;
    private javax.swing.JTextField textoPreguntas;
    // End of variables declaration//GEN-END:variables
}
